version: '3'
services:

  jupyter:
    build: ./jupyter-notebook
    container_name: 'jupyter'
    volumes:
      - ./notebooks:/home/jovyan/work
      - $PWD/mlflow:/home/jovyan/work/mlflow
      - $PWD/mlflow-artifacts:/mlflow-artifacts   # ajouter ce volume
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      JUPYTER_TOKEN: 'Mettre token passeword'
    command: [start-notebook.sh, "--NotebookApp.token='Mettre token password'"]
    user: "1000:1000"   # ajouter cette ligne
    depends_on:
      - mlflow

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: 'mlflow'
    user: "1000:1000"   # Remplacez 1000 par l'ID utilisateur et le groupe de l'utilisateur jovyan sur votre système.
    command: ["mlflow", "server", "--host", "0.0.0.0", "--backend-store-uri", "file:///home/jovyan/work/mlflow/backend"]
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: "file:///home/jovyan/work/mlflow/backend"
    volumes:
      - $PWD/mlflow:/home/jovyan/work/mlflow:rw
      - $PWD/mlflow-artifacts:/mlflow-artifacts   # ajouter ce volume

  mlflow-ui:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: 'mlflow-ui'
    command: ["mlflow", "ui", "--backend-store-uri", "file:///home/jovyan/work/mlflow/backend"]
    ports:
      - "5001:5000"
    depends_on:
      - mlflow

  mongo-express:
    image: mongo-express
    container_name: 'mongoadmin'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_BASICAUTH_USERNAME: 'Mettre Username'
      ME_CONFIG_BASICAUTH_PASSWORD: 'Mettre password mongo-express'
    links:
      - mongo

  mongo:
    image: mongo
    container_name: 'mongo'
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
