version: '3.3'

services:
    fastapi:
        build: fastapi/
        command: uvicorn main:app --host 0.0.0.0 --port 8008
        volumes:
            - ./:/usr/src/app
        ports: 
            - 8008:8008 
        networks:
            - deploy_network
        container_name: fastapi

    streamlit:
        build: streamlit/
        command: streamlit run main.py
        volumes:
            - ./:/usr/src/app
        depends_on:
            - fastapi
        ports: 
            - 8501:8501
            
        networks:
            - deploy_network
        container_name: streamlit

networks:
    deploy_network:
        driver: bridge





