global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['<Public IPv4 DNS>:8008'] # Mettre Ip public Aws EC2
        labels:
          __scheme__: http
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']
